readme

diff --git a/bin/bundle b/bin/bundle
--- a/bin/bundle
+++ b/bin/bundle
@@ -1,5 +1,10 @@
 #!/usr/bin/bash
 
+if ! command -v pp &> /dev/null; then
+    echo "Error: 'Par::Packer' is not installed."
+    exit 1
+fi
+
 script_dir="$(dirname "$(realpath "$0")")"
 
 pp -x -c "$script_dir/../src/run.pl" -o "$script_dir/../froogle"
